tweag/topiary

- .github/workflows/ci.yml
* Node.js 12 support deprecated\
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
* `save-state` command deprecated\
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
The macOS 12 warning is still a thing, but it's a preparatory warning, rather than a deprecation.
> Bump action versions to resolve deprecation warnings

- src/atom_collection.rs
This is a first step wrt solving #90. Panicking is a little extreme, but it's better than nothing; the ultimate goal (in PRs to come) is to make encountering unknown capture groups a parse error and bail-out gracefully.
> Deal with unknown capture names when resolving query

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This implements the parts missing to support the first-class module example given by Niols in #106.
It includes: 
- dealing with the line breaks between declaration of different natures, 
- opening the indentation for module signature which is closed by the `end` keyword 
- removing the spaces between parentheses and keywords. This last bit is not working as expected, due to a bug in tree-sitter queries: https://github.com/tree-sitter/tree-sitter/issues/1811 . There are 3 options to deal with it: 
1. Chose that we always want spaces around parentheses (quite unusual in the OCaml world, but the default in many languages), 
2. Write the queries in a not elegant, but bug-avoiding way,
3. Spend time working on the tree-sitter repository to fix the issue upstream.
The [golden rule of software …
> Support first-class module

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Adds the "and" keyword where it was missing and allows blank lines between several mutually recursive definitions.
> Handle mutually recursive functions

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Adds the "include" keyword where it was missing and add line breaks after module inclusions.
> Handle module inclusion

- Cargo.lock
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Since this issue https://github.com/tree-sitter/tree-sitter-ocaml/issues/63 was solved upstream, we have to update the lockfile to bring those changes to Topiary.
This finally allows us to have polymorphic types in the Ocaml syntax we support!
> Update lockfile and add example with polymorphic types

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Add a line break after = in multiline definition, both to be faithful with the presented example and to have an idempotent formatter.
> Add line break after equal for multiline definition

- .gitignore
- CONTRIBUTING.md
- README.md
- generate-coverage.sh
This PR documents how one can generate an HTML code coverage report using LLVM profiling data. It also provides a script, for Nix users, to do this automatically without (hopefully) polluting their environment.
This goes towards #80, but has not been added to the CI as it flaunts the usual Nix Flake-based distribution. (See that issue for discussion.)
> Document generation of code coverage report

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Adds spacing and line breaks for `let`-like and `and`-like operators.
This allows the following to be correctly formatted:
```
let greetings =
let (let*) = Option.bind
and (and*) a_opt b_opt =
match (a_opt, b_opt) with
| (Some a, Some b) -> Some (a, b)
| _ -> None
in
let* msg1 = Some "hello "
and* msg2 = Some "world"
in
Some (msg1 ^ msg2)
```
> Ocaml support for bound operators

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This allows the following to be correctly formatted:
```
let Some foo = Some bar
```
Closes #139
> [OCaml] Support constructors in assignment lhs

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows the following to be formatted correctly:
```
let quoted_string =
{|Hello|}
print_endline quoted_string
```
> [OCaml]: Support for quoted strings

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
let my_const : 'a 'b. 'a -> 'b -> 'a = Fun.const
```
> [OCaml] Support for type variables

- Cargo.lock
- Cargo.toml
- languages/bash.scm
- src/language.rs
- src/tree_sitter.rs
- tests/sample-tester.rs
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR adds vacuous Bash support. That is, it brings in all the dependencies and contains the necessary changes to the codebase to support Bash, but the query file for Bash contains no formatting directives and the sample files (input and expected) just have their shebang lines; these will be expanded in subsequent PRs.
(I also took the opportunity to update the input vs. expected test runner to use the language detection code.)
> Bash support (POC)

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows correct formatting of object-oriented code, like the following:
```
module Inner1 = struct
class ['a] pushable =
object (self)
val mutable list = ([]: 'a list)
method push x =
list <- x::list
end
class virtual ['a] poppable =
object (self)
inherit ['a] pushable
(* unsafe implementation *)
method pop =
let result::rest = list in
list <- rest;
Some result
end
end
module Inner2 = struct
class type ['a] stack =
object
inherit ['a] Inner1.poppable
end
class ['a] stack_impl : ['a] stack =
object
inherit ['a] Inner1.poppable as super
(* safe implementation *)
method pop =
match list with
| _::_ -> super#pop
| _ -> None
end
end
let (Some 2) =
let my_stack = new Inner2.stack_impl in
my_stack#push 1;
my_stack#push 2;
my_stack#pop
```
Note that I'm not very familiar with OCaml's …
> [OCaml] Support object-oriented programming

- Cargo.lock
- Cargo.toml
- languages/rust.scm
This PR updates tree-sitter-rust to v0.20.3, which removes support for `if_let_expression` directives. This has been obviated by an improved `if_expression`.
Resolves #147
> [Rust] Fix query after tree-sitter-rust update

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
let unbox_rec = function
| Some My_types.{ my_bool } -> my_bool
| _ -> false
```
> [OCaml] fix spacing issues with local imports

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This will allow the following to be formatted correctly:
```
module type T1 = sig
type t = private int64
end
module type T2 = sig end
module M: T2 = struct end
module F (X: T1) (Y: T1 with type t := X.t) = struct
module type S = sig
type t = X.t
val zero : t
val succ : t -> t
include T2
end
let zero = 0
let succ n = n + 1
include T2
end
```
> [OCaml] miscellaneous improvements on module/functors formatting

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
function -1 -> -1
```
Closes #153
> [OCaml] fix disappearing negative numbers

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows the following to be formatted correctly:
```
let unbox_bool = function
| Some true -> true
| _ -> false
```
> [OCaml] Add spacing for booleans

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
let my_const : type a b. a: a -> b: b -> a = fun ~a ~b -> a
```
> [OCaml] add spacing in polymorphic types

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
let obj_id (obj : < .. >) = obj
let obj_with_unit_id (obj : < nothing: unit; .. >) = obj
let obj_with_only_unit_id (obj : < nothing: unit >) = obj
```
> [OCaml] spacing in object signatures

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```
let into_list ~value = my_id ~value :: []
```
> [OCaml] spacing before `::` when preceded by labeled argument

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This PR fixes spacing issues in OCaml with
- the type coercion operator `:>`,
- the range pattern `'a'..'z'`,
- nested constructor patterns.
> [OCaml] fix several spacing issues

- README.md
- src/atom_collection.rs
This PR implements the `@prepend_hardline` capture group, for completeness' sake, and provides more detailed documentation of the various newline types to aid understanding.
> @prepend_hardline and further documentation of different newline types

- README.md
- benches/benchmark.rs
- languages/ocaml.scm
- src/language.rs
- src/lib.rs
- src/main.rs
- src/tree_sitter.rs
- tests/sample-tester.rs
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.mli
This PR changes the way languages are processed in Topiary.
To properly process an input stream, we need two things:
- a grammar, to produce a syntax tree from the input,
- a query file, to format this syntax tree.
Additionally, we use the intermediate notion of `Language`, which is represented by an enum type internally.
The CLI for Topiary ensures we get at least one of the following arguments:
- `--language`, to specify the language of the input stream,
- `--query`, to specify which query file to use,
- `--input-file`, to specify a file from which to read the input.
If `--input-file` is missing, Topiary reads from `stdin`.
We follow the following steps to determine the grammar and the query:
First, we determine the language:
- if the `--language` argument is present, use it,
- else if …
> [OCaml] support for `.mli` files

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/lib.rs
- src/pretty.rs
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This command simply deletes a node.
I do not think that deleting a non-trivial node will ever be useful, but this allows us to move things around.
The need for it occurred to me when dealing with Ocaml records. Currently, we are adding a semi-colon after the last field. This is precisely the kind of decision a developer does not want to take, so it seems reasonable to me that topiary adds it.
But what if there is a comment right after the field declaration. Should the semicolon come before or after it? That's also the kind of micro-decision the formatter should take care of.
To do so, we have to suppress the semicolon before comments and put it after.
PS: I realize that this pull request both implement the new comment and the use-case described. It is part of the same story in my mind, …
> Add a @delete command

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
This addresses #133 by adding the new line after the "in" in let definition rather than having it before some very specific constructs.
Same for "=" and "with", there are already some line breaks added depending of the context (ie ancestor node) in which these symbols occur, and it seems more principled to have it this way and made the incriminated query redundant.
@aspiwack I know that you do not like the formatting of `add_three_lines`, but as I mentioned in https://github.com/tweag/topiary/pull/127#issuecomment-1351770298 I do not see how to format it differently with the current set of command.
Of course, adding a new command would not be hard at all, but I do not see it as a priority.
Closes #133 .
> Allow line break after 'in' and "while"

- README.md
- languages/bash.scm
- playground.sh
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces queries that improve support for command, command lists and command pipelines, in aid of #138. It is outputting valid code, but suffers from some (non-blocking, imo) shortfalls:
* The line-spacing is not perfect;
* Multi-line "commands" are collapsed into a single line (see #172)
I have also cleaned-up and checked-in the script -- with documentation -- I created to support interactive query development in the terminal (as a quick-and-dirty alternative to #171); it seems generally useful.
> [Bash] More command formatting

- languages/bash.scm
- playground.sh
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces support for the various forms of Bash loops, in aid of #138:
1. Classic `for` loops
2. C-style `for` loops
3. `select` loops
4. `while` loops
5. `until` loops
:bulb: This PR builds upon the following; do not merge until its ancestors have landed.
> [Bash] Loops

- languages/bash.scm
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces formatting for Bash `case` switch statements, in aid of #138.
> [Bash] Switch statements

- languages/bash.scm
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces formatting queries for compound statements (i.e., between curly-parentheses) and subshells (i.e., between parentheses), in aid of #138. It's worth pointing out the following:
1. Both compound statements and subshells are "units of execution"; i.e., they can appear anywhere a basic command can appear. Usually a unit of execution is given its own line, except in the case of the condition to an `if` statement.[^1] This is making the list of queries that express the contexts for units of execution -- and the alternation that defines them -- particularly long... I _think_ that is all of them, now :crossed_fingers:
2. Both compound statements and subshells can (and regularly do) appear in a single-line context. As such, unit spacing is done within these using spaced …
> [Bash] Compound statements and subshells

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows proper formatting of
```
List.fold_left
(explore (node::path))
visited
(List.map Files_legacy.get_file edges)
```
Also, remove redundant rules and fix nonsensical example in OCaml input.
> [OCaml] Indentation and softlines in multiline function calls

- languages/bash.scm
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces formatting queries for function definitions, variable declaration and variable assignment, in aid of #138.
Note: It would be _really_ nice to be able to write a query that can convert "simple expansions" (e.g., `$foo`) into full, unambiguous expansions (i.e., `${foo}`) as a stylistic choice; similar to how I'm forcibly removing the redundant `function` keyword. I played around with inserting delimiters, but couldn't make anything work :cry:
> [Bash] Functions and variables

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows correct formatting of
```
fun
(long_argument_1 : int)
(long_argument_2 : int)
(long_argument_3 : int)
(long_argument_4 : int) ->
()
```
Note that with this PR, there will be a double indentation on the second line of
```
let f = fun
x -> x
```
I think the code is still more correct with the PR, and we'll be able to address the double indentation problem in a separate issue.
This PR also simplifies queries for let bindings.
> [OCaml] identation and softlines in anonymous functions

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows correct formatting of
```
let _ =
let open Printf in
sprintf "hello world"
```
> [OCaml] Don't indent after open modules in let open

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows correct formatting of
```
(
1,
2,
3,
4
)
```
Note: because tuples in OCaml are actually left-associative couples, the following is formatted as above:
```
(
1,
2,
3, 4
)
```
but the following is left as-is:
```
(
1, 2,
3,
4
)
```
> [OCaml] indent and allow softlines in tuples

- languages/bash.scm
- tests/samples/expected/bash.sh
- tests/samples/input/bash.sh
This PR introduces formatting support for the following Bash constructs, in aid of #138:
* New line after multi-line syntactic blocks (e.g., `if` statements, subshells, etc.)
* New line after a run of "units of execution" (± a few others) before a multi-line syntactic block or variable
* New line after a run of variable declarations or assignments.
Notes:
* Process substitution "just works", without requiring special rules.
* There is an (unassailable) problem with heredocs having their first line affected by the indent level.
* This PR fixes new lines for variable assignment outside of declaration contexts. This further complicates the "unit of execution" alternation and speciation, given the lack of negative anchors in the Tree Sitter query language.
> [Bash] Redirection, herestrings, heredocs, command and process substitution

- languages/bash.scm
- tests/samples/expected/bash.sh
This PR reverses the new line strategy from prepending to appending, this has two benefits:
1. The intention is clearer (i.e., it's more familiar to think of appending new lines to the end of a node than prepending one to its beginning).
2. In theory, it should make the rules for comments easier/possible to write. In particular, the prepending strategy conflicts with how to deal with trailing comments. (Rules for comments will be addressed in a subsequent PR: #186.)
Notes:
* The only way I could get indentation blocks to work correctly (see https://github.com/tweag/topiary/pull/182#discussion_r1083931668) was to prepend a new line before the block's closing node. When this is preceded by a node that appends a new line, you end up with a blank line in between, like this:
```bash
while …
```
> [Bash] Reverse new line strategy

- .github/settings.yml
I've specified issue tags for various language formatting issues, rather than prefixing the issue title with "[Language]".
> Added issue tags for language specific formatting

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows proper formatting of
```ocaml
let _ =
[
1;
2;
3
]
```
Ideally, we would want to add a final `;` to multiline lists, but we don't have the capacity to do that yet: see #199.
Closes #189
> [OCaml] List formatting

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/lib.rs
- src/pretty.rs
- tests/samples/expected/ocaml.ml
The matched nodes will have a multiline-only delimiter appended to them.
It will be printed only in multi-line nodes, and omited in single-line nodes. The delimiter must be specified using the predicate `#delimiter!`.
```scheme
; Add a semicolon at the end of lists only if they are multiline, to avoid [1; 2; 3;].
(list_expression
(#delimiter! ";")
(_) @append_multiline_delimiter
.
";"? @do_nothing
.
"]"
.
)
```
This allows proper formatting of the following:
```ocaml
let _ =
[
1;
2;
3;
]
let _ = [1; 2; 3]
```
Closes #199
> Introduce `prepend/append_multiline_delimiter`

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/lib.rs
- src/pretty.rs
- src/tree_sitter.rs
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
- tests/samples/input/ocaml.mli
This PR introduce scope commands and softlines.
This allows to open a scope with a query, close it with another, and add softlines that expand if and only if their encompassing scope is multi-line.
In essence, it allows to add the "multiline tag" to broader subsets of nodes than just single nodes of the AST.
For instance, to format OCaml tuples, you can use the following queries:
```
(parenthesized_expression
.
"(" @begin_scope
(#scope_id! "tuple")
)
(parenthesized_expression
(#scope_id! "tuple")
")" @end_scope
.
)
(product_expression
"," @append_spaced_scoped_softline
(#scope_id! "tuple")
)
```
TODO:
Closes #190 
Closes #87
> Introduce custom scopes and scoped softlines

- languages/bash.scm
- tests/samples/expected/bash.sh
This PR fixes the errant spacing added to command substitutions that are within strings that could lead to syntactically invalid output.
Notes:
* Resolves #201
> Fix spacing before interpolated command substitutions

- languages/ocaml.scm
- tests/samples/expected/ocaml.mli
Allows the following to be kept as it is:
```ocaml
module Foo : sig
val foo: int
end
```
Closes #191
> Don't enforce line break after ":" in module bindings

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows proper formatting of:
```ocaml
open Foo
open Bar
let _ =
let open Baz in
()
```
Closes #214
> [OCaml] Line break after top-level open module

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows the following:
```ocaml
type t = {
foo: bool [@default false];
bar: int
}
type t = {
foo: bool;
bar: int [@default 0]
}
type t = {
foo: bool;
bar: int [@default 0] (* comment *);
}
```
to be formatted as:
```ocaml
type t = {
foo: bool [@default false];
bar: int;
}
type t = {
foo: bool;
bar: int [@default 0];
}
type t = {
foo: bool;
bar: int [@default 0]; (* comment *)
}
```
Closes #220
> [OCaml] Integrate ppx attributes in field declarations

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows correct formatting of
```ocaml
module Lift
(Credit: module type of CreditSignature)
(Dance: module type of DanceSignature)
(Tune: module type of TuneSignature)
(Version: module type of VersionSignature)
= struct
let foo = x
end
```
Closes #217
> [OCaml] Softlines and indentation in functor arguments

- src/error.rs
- src/lib.rs
This PR changes the error message when there is an idempotency failure by outputting the colourised diff, as before, but without panicking.
Error style before change:
Error style after change:
Resolves #221
> Write out the diff to the error log, rather than panicking

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats
```ocaml
type t = {
bar: float;
foo: bool [@default false] (* a comment *) [@other tag] (* and another one *)
[@and again] (* and another one *) [@and again] (* and a last one *);
}
```
into
```ocaml
type t = {
bar: float;
foo: bool
[@default false] (* a comment *)
[@other tag] (* and another one *)
[@and again] (* and another one *)
[@and again]; (* and a last one *)
}
```
Closes #225
Closes #224
> [OCaml] Multi-line attributes after field declarations

- languages/ocaml.scm
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.mli
Correctly formats
```ocaml
val foo : bar -> baz
val other_foo : bool -> float
```
Closes #229
> [OCaml] line breaks between value specifications

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats
```ocaml
let [|a; _; _|] = [|1; 2;
3|]
```
as
```ocaml
let [|a; _; _|] =
[|
1;
2;
3;
|]
```
Closes #230
> [OCaml] Indentation and softlines in arrays

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
```ocaml
let long_function
(long_argument_1 : int)
(long_argument_2 : int)
(long_argument_3 : int)
(long_argument_4 : int)
: unit
=
()
let large_const =
let val = 3 in
fun
(long_argument_1 : int)
(long_argument_2 : int)
(long_argument_3 : int)
(long_argument_4 : int)
: int
->
val
```
Closes #219
> [OCaml] improve formatting of multiline function definitions

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats
```ocaml
let _ = (let x = 42 in
x)
```
as
```ocaml
let _ =
(
let x = 42 in
x
)
```
Closes #218
> [OCaml] indendation and softlines in parenthesized expressions

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
Fixes several spacing policies, mainly by removing specific spacing rules, and adding items to the big "list of stuff that must be separated by spaces" query.
Among others, allows correct formatting of
```ocaml
type query = (string * string list) list
type x = ('any Slug.t -> bool) -> float
let id (type s) (x : s) : s = x
type foo = { a: 'a. ('a, mandatory) arg -> 'a; }
type foo = (int, int) result
```
Closes #215
Closes #245
Closes #246
Closes #247
Closes #250
> [OCaml] fix and simplify spacing policy

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats
```ocaml
let x = foo || foo
|| bar || bar
let x = foo; foo;
bar; bar
```
as
```ocaml
let x =
foo
|| foo
|| bar
|| bar
let x =
foo;
foo;
bar;
bar
```
Closes #251
> [OCaml] Scoped softlines for sequences and infix expressions

- README.md
- default.nix
- src/error.rs
- src/language.rs
- src/lib.rs
- src/main.rs
- tests/cli-tester.rs
This PR:
We cannot distinguish, from `std::io::Error`, between a read error or a write error. This was returning invalid `WritingError`s, e.g., when attempting to read a query file that did not exist.
As such, `ReadingError` and `WritingError` have been consolidated into `IoError`, which has two subtypes: `Filesystem` (which correlates directly to `std::io::Error`), and `Generic` (which is a "catch all" for everything else).
Error outputting is now done with logging, rather than `eprintln!`.
Using the same priority order as before (runtime envvar > build time envvar > `./languages`), also check if the query file exists. If it does, at whatever level, then all is well; otherwise, return an error.
Resolves #256
> Improvements to error handling and determining the location of query files

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats
```ocaml
let x = foo;%lwt bar
let x =
foo;%lwt bar;%lwt
baz;%lwt qux
let x =
foo
bar;%lwt
baz
let x = function
| [%type: [%t? foo] option] ->
bar
```
as
```ocaml
let x = foo;%lwt bar
let x =
foo;%lwt
bar;%lwt
baz;%lwt
qux
let x =
foo
bar;%lwt
baz
let x = function
| [%type: [%t? foo] option] ->
bar
```
Closes #265
Closes #268
> [OCaml] Fix ppx spacing and softlines

- src/lib.rs
- tests/samples/expected/bash.sh
This PR changes the whitespace trimmer such that it:
1. Trims whitespace from the end of each formatted line (as before)
2. Trims any leading and/or trailing new lines
3. Reinstates the new line at EOF.
Note: The formatted output assumes Unix-style new lines (`\n`). That's no change from before this PR, but this could probably be improved to accommodate the different platforms'/input file's new line expectations.
Resolves #48
> Remove leading and trailing blank lines

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
Leaves the following as is:
```ocaml
let kind c =
if is_letter c then Letter
else if is_digit c then Digit
else if is_space c then Space
else if is_symbol c then Symbol
else Other
```
Closes #252
> [OCaml] process "else if" as an "elif" keyword

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
Formats the following as is:
```ocaml
module MOption:
functor (A: SERIALISABLE) -> SERIALISABLE with
type t = A.t option
module MUnit: SERIALISABLE with
type t = unit
```
Closes #249
> [OCaml] Fix module indentation

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
Add correct support for the following:
```ocaml
type (+'meth, 'prefix, 'params, 'query, 'input, 'output) service =
('meth, 'prefix, 'params, 'query, 'input, 'output, error) raw
constraint 'meth = [< meth]
```
> [OCaml] Support type constraints and polymorphic syntax

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Formats the following as is:
```ocaml
let x =
let module IMap = Map.Make(Int) in
IMap.empty
```
Closes #255
> [OCaml] no hardlines after `let module`

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This PR supersedes #278 and #279, to simplify the commit history after bad rebases:
* Resolves #231 
* Resolves #233
Notes:
* The `function`/`match` rule looks a little bit too general and may "over-format". It works on the minimal examples, but I cannot speak to how it affects other `(expression_item)` nodes.
* The history is still a bit of a mess :confounded: Best to just review the diff from `main`.
> Fix various PPX indentation issues

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
> Handling of indentation for modules with a `with`

- languages/ocaml.scm
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.mli
Allows the following to be left as is:
```ocaml
include module type of (struct include Time end)
```
Closes #290
> [OCaml] Don't always enforce line break after `include_module`

- languages/ocaml.scm
- src/atom_collection.rs
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows the following:
```ocaml
module Make (R : sig end)
(S : sig end) (T : sig end)
```
to be formatted as
```ocaml
module Make
(R: sig end)
(S: sig end)
(T: sig end)
```
Also, closes #289
> Fix panic and improve formatting of module bindings

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/configuration.rs
- src/lib.rs
- src/pretty.rs
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
The matched node will be printed alone, on a single line, with no indentation.
```scheme
(#language! ocaml)
; line number directives must be alone on their line, and can't be indented
(line_number_directive) @single_line_no_indent
```
With this PR, the following
```ocaml
module Foo = struct
val bar
end
```
will be formatted as
```ocaml
module Foo = struct
val bar
end
```
The loss of the line break is a bit of a pity, but given the low usage of the line number statement, I don't think it matters that much. We'll open a low-priority issue if we deem it necessary.
Closes #287
> Introduce `@single_line_no_indent` predicate

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/expected/ocaml.mli
- tests/samples/input/ocaml.ml
* No longer enforce final semicolon, which led to incorrect behavior (see #263)
* Force semicolons to come before comments *and* attributes
* Correctly format `(field_declaration) ";" (attribute)`
Closes #288
Closes #292
> [OCaml] Several fixes about records

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Format the following
```ocaml
let foo = function
| x -> (
try foo with _ -> None )
let f = function
| None -> ()
| Some x ->
(match x with None -> () | Some _ -> ())
let foo = function
| Some _ ->
(function true -> false | false -> true)
| None ->
(function true -> true | false -> false)
```
as
```ocaml
let foo = function
| x ->
(
try foo with _ -> None
)
let f = function
| None -> ()
| Some x ->
(match x with None -> () | Some _ -> ())
let foo = function
| Some _ ->
(function true -> false | false -> true)
| None ->
(function true -> true | false -> false)
```
Closes #291
Closes #293
> [OCaml] Remove wrong line breaks in nested match cases

- languages/ocaml.scm
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
Allows the following to be formatted as is:
```ocaml
let _ =
x <-
if foo then
bar
else
baz
```
Closes #306
> [OCaml] Support set expressions

- Cargo.lock
- Cargo.toml
- src/pretty.rs
* Get rid of `RcDoc`, as we no longer need its capabilities.
* Streamilne the pretty-printing function.
* Return errors instead of panicking or silently clipping output.
Closes #299
> Refactor pretty-printer

- src/configuration.rs
- src/pretty.rs
This commit doesn't really provide anything of substance over PR #307. The most significant change is that the `write!` calls are handled directly in the `match` branches, rather than allocating a new string. Besides that, I've made some light formatting changes to make the big `match` slightly easier to follow.
**tl;dr** Take it or leave it!
---
**Update** Also superficial, but I fixed the Clippy warnings in `src/configuration.rs` too.
> Superficial refactor of the refactored pretty-printer

- src/bin/topiary/error.rs
- src/bin/topiary/main.rs
- src/bin/topiary/output.rs
- src/error.rs
This is the beginnings of #303, as a piecemeal migration to separated codebases.
Notes:
* This is just a surface-level separation. There are still functions of the library that should be handled by the CLI, whose error handling code needs to remain before these functions are extracted. (Marked with comments.)
* The piecemeal nature of the migration means there is a certain amount of redundant/duplicated code. This is a crutch, to ensure a clean build, until the migration is complete.
> Separate error handling code for binary

- src/atom_collection.rs
- src/tree_sitter.rs
Decreases the processing time of larger OCaml files from ~7s to ~1.6s
> [perf] Store query matches locally to avoid running query twice

- README.md
- languages/bash.scm
- languages/nickel.scm
- languages/ocaml.scm
- languages/rust.scm
- languages/toml.scm
- languages/tree-sitter-query.scm
- src/language.rs
- tests/sample-tester.rs
- tests/samples/expected/tree-sitter-query.scm
- tests/samples/input/tree-sitter-query.scm
This PR adds support for the tree-sitter query language:
* Add a query file and the boilerplate to support `.scm` files as input
* Format our query files with Topiary
* Add a test to check that our query files are properly formatted
Closes #101
Based upon #315 for the tree-sitter query grammar
> Support tree-sitter query language

- src/bin/topiary/main.rs
- src/configuration.rs
- src/error.rs
- src/language.rs
- src/tree_sitter.rs
- tests/sample-tester.rs
The original purpose of this PR was to expose extension points to Tree-sitter's parser, at the library level, such that the binary could emit a serialised form of the parsed tree (i.e., to satisfy #11). After much thought, however, it is my opinion that it is _not_ the library's job to provide this and is only offered by the binary as a "nice-to-have". Specifically:
* Walking the syntax tree in Tree-sitter is relatively straightforward. Serialising the output is a harder task, but has nothing to do with formatting.
* Exposing Tree-sitter is no different from using Tree-sitter directly.
* As such, if the exposure was to provide an interface -- presuming, for the sake of argument, it's the library's responsibility -- then we'd have the job of reimplementing or wrapping Tree-sitter's …
> Refactor Language interface

- README.md
- flake.nix
This PR adds to the flake an output `lib.${system}.pre-commit-hook` that contains a configuration allowing to use Topiary in [pre-commit-hooks.nix](https://github.com/cachix/pre-commit-hooks.nix). It is a first draft and I am fine changing everything again. In particular:
- I only enabled the pre-commit-hook on `.json`, `.toml`, `.ml` and `.mli` files (and not on `.sh` files). For that I based myself on the output of `--help` that mentions the legal uses of `--language`. I am happy to add `.sh` to the list of matched files.
- The bit of documentation the README is quite prominent, maybe too much for what this is. It made sense to me to put it in the “getting started” section. Maybe it should move after the usage examples though?
> Add `pre-commit-hooks.nix` integration in the flake

- .github/workflows/ci.yml
The failing CI problem is fixed in #324, but to resolve it sooner, I've cherry-picked the commit into this PR.
> Cherry-picked commit to fix the CI

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/lib.rs
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This PR introduces a new formatting predicate, `singleline_delete`, which deletes a node only if the context is single-line. It also uses this new predicate, along with `prepend_multiline_delimiter`, to enforce the following rule in OCaml:
**The optional `|` before the first match case must be present if and only if the context is multi-line.**
Formats
```ocaml
let not = function
true -> false
| false -> true
let not = function | true -> false | false -> true
```
as
```ocaml
let not = function
| true -> false
| false -> true
let not = function true -> false | false -> true
```
TODO:
Closes #281
> Enforce opinion about optional `|` before first match case

- CHANGELOG.md
- MAINTAINERS.md
Updated changelog and release notes with the release names and instructions, applying names retrospectively.
> Release names

- README.md
- languages/ocaml.scm
- src/atom_collection.rs
- src/lib.rs
- tests/samples/expected/ocaml.ml
- tests/samples/input/ocaml.ml
This PR introduces two new formatting directives, which use custom scopes:
- `@append_scoped_multiline_delimiter` / `@prepend_scoped_multiline_delimiter`, which are the equivalent of `@*pend_multiline_delimiter`, but check if a custom scope is multi-line instead of the parent node.
- `@singleline_scoped_delete`, which is the equivalent of `@singleline_delete`, but checks if a custom scope is multi-line instead of the parent node.
These directives are used to fix the OCaml query file, which can now format
```ocaml
let not =
function true -> false | false -> true
```
into
```ocaml
let not = function
| true -> false
| false -> true
```
in a single pass, instead of two previously.
Closes the OCaml part of #334:
```
cargo run -- -f tests/samples/input/ocaml.ml
```
> Add new formatting directives to solve OCaml idempotency issue

- src/graphviz.rs
The node kind was escaped in the original GraphViz output. However, for anonymous nodes that contained escapable whitespace characters (e.g., `\n`), these ended up getting reinterpreted by GraphViz as their corresponding whitespace. That wasn't very helpful in the output, so now these characters are double-escaped, so they can be scrutinised.
> Improve the escaping for GraphViz output

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- benches/benchmark.rs
- default.nix
- flake.lock
- flake.nix
- src/bin/topiary/main.rs
- src/error.rs
- src/language.rs
- src/lib.rs
- src/tree_sitter.rs
- tests/sample-tester.rs
Related to #171 .
`web_tree_sitter::Language::load_path()` is async, so now Topiary is as well. It's not entirely straightforward to make `formatter()` async, and it may be nice to keep the async stuff out of it anyway, so the API has changed so that grammars are loaded outside of it, then passed in to `formatter()`.
Also added Wasm building to Nix, and running that from CI.
> Compile Wasm

- benches/benchmark.rs
- src/bin/topiary/error.rs
- src/bin/topiary/main.rs
- src/lib.rs
- tests/sample-tester.rs
- web-playground/src/lib.rs
Change the `formatter` API such that it takes the query as a `&str`, rather than `io::Read`. Previously, the `BufReader` was getting drained in `src/bin/topiary/main.rs` to parse the configuration, leaving the formatter with an empty query buffer.
> Fix premature draining of query buffer

- tests/cli-tester.rs
Modify `cli-tester.rs` such that it confirms that _some_ formatting (hopefully the correct formatting) has occurred. This should catch the error fixed by PR #343.
Resolves #344
> Test that formatting happens

- README.md
- flake.nix
- src/bin/topiary/error.rs
- src/bin/topiary/main.rs
This PR distinguishes exit code by error type, documented in the `README`. Largely motivated by the need, raised by @Niols, to skip over language detection errors in the precommit hook script (which has also been updated, accordingly).
> Convert error types into productive exit codes

- playground.sh
- topiary/tests/sample-tester.rs
- topiary/tests/samples/expected/bash.sh
- topiary/tests/samples/input/bash.sh
This PR:
* Resolves the idempotency errors in the Bash integration tests (by commenting them out, for now...)
* Switches on the idempotency checking in the integrations tests.
Resolves #334
> Resolve integration test idempotency

- Cargo.lock
- README.md
- languages/nickel.scm
- topiary-cli/src/supported.rs
- topiary/Cargo.toml
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
This PR introduces:
This will flow `|`-annotations on to new lines, when the annotations as a whole cover multiple lines. It will not reflow type annotations, because they can be nested and this causes idempotency issues (there doesn't appear to be a way of establishing the depth of the nesting from the grammar alone). For example:
```nickel
{
single-line : type | annot | annot = whatever,
multi-line : type
| annot
| annot
= whatever
}
```
For let bindings, the RHS will appear indented, on a new line, if it covers multiple lines:
```nickel
let single-line = fun x => x
let multi-line =
fun x => x
```
Likewise for function definitions:
```nickel
let multi-line-function =
fun x =>
x
```
Miscellaneous stuff:
* Allow blank lines between record fields.
* Designate builtins as leaves so their …
> Nickel: Annotations

- README.md
- topiary/src/atom_collection.rs
- topiary/src/lib.rs
The PR introduces the concept of "antispaces", that can be inserted into the formatting stream with the `@append_antispace` and `@prepend_antispace` capture names. When an `Antispace` atom is encountered during post-processing, it and any runs of preceding and/or succeeding `Space` or `Antispace` atoms are removed from the stream. This ultimately allows spacing exception rules to be written more easily.
For example, if we define the JSON formatting rules such that _any_ named node is surrounded by spaces, this upsets the spacing around list and pair delimiters. However, we can now fix that easily with an antispace:
```scheme
(#language! json)
(string) @leaf
(_) @append_space @prepend_space
":" @prepend_antispace
"," @prepend_antispace @append_empty_softline
(object
.
"{" …
```
> Implemented antispaces

- languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
* Don't add spaces before `,`, `;` and `.` delimiters[^1]
* Don't add spaces immediately inside parentheses
* Don't surround record opening/closing tokens with spaces
* Don't add spaces/newlines to empty records
[^1]: I've been liberal, here. I don't know if all these delimiters are attested.
> Nickel spacing tweaks

- topiary/src/atom_collection.rs
This PR removes `topiary::atom_collection::ensure_final_hardline`, as it is redundant. The whitespace trimmer (`topiary::lib::trim_whitespace`) -- which happens after post-processing -- will strip the `\n` added by `ensure_final_hardline` and then reinstates it.
https://github.com/tweag/topiary/blob/d9e0a72a60be911cfa5de98d3207a0833fb9b15a/topiary/src/lib.rs#L214-L219
> Remove ensure_final_hardline from post-processing

- languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
* Removed the head node restrictions on anything that looks like a container type.
* Created a scope for all containers, to apply delimiter spacing consistently.
* Only add spacing inside an array when there are _two_ or more elements. It's common to see single element arrays use short tokens with no spacing, in hand formatted code (e.g., `[x]`).
> Tidy up and generalise Nickel container type formatting

- README.md
- languages/ocaml.scm
- topiary/src/atom_collection.rs
- topiary/src/lib.rs
- topiary/src/tree_sitter.rs
Sometimes, similarly to what happens with softlines, we want a query to match only if the context is single-line, or multi-line. This PR introduces several predicates that achieve this result.
These predicates allow the query to trigger only if the matched nodes are in a single-line (resp. multi-line) context.
```scheme
; Allow (and enforce) the optional "|" before the first match case
; in OCaml if and only if the context is multi-line
(
"with"
.
"|" @delete
.
(match_case)
(#single_line_only!)
)
(
"with"
.
"|"? @do_nothing
.
(match_case) @prepend_delimiter
(#delimiter! "| ")
(#multi_line_only!)
)
```
These predicates allow the query to trigger only if the associated custom scope containing the matched nodes are is single-line (resp. multi-line).
```scheme
; Allow (and enforce) the …
```
> Introduce conditional predicates to reduce number of directives

- topiary/src/atom_collection.rs
- topiary/src/tree_sitter.rs
Using borrows where possible is less restrictive, and allows for less cloning of data.
> Use borrows where possible

- Cargo.lock
- README.md
- languages/rust.scm
- topiary/Cargo.toml
- topiary/src/configuration.rs
- topiary/src/lib.rs
- topiary/src/pretty.rs
Resolves #105 
I was/am not sure about the regular expressions parsing of the arguments. They used to support multiple arguments, but I've reduced that to 1 because I could not reconcile that easily with "   " string arguments.
Escaping is done by an old crate, but more modern alternatives are all GPL licensed. This isn't an issue to us, but could be a problem to future users of our library.
> Support arbitrary indentation (#105)

- languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
**Note** There is an idempotency issue with `let` expressions. However, the case in which it occurs is quite specific; it is not, for example, manifested by the Nickel standard library. It is documented in the query file and I will add an issue, but it shouldn't be a blocker for this PR.
> Odds-and-ends of Nickel formatting

- languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
This PR makes a small tweak to the formatting of parentheses. Namely, if their contents are multi-line, then that starts an indentation block on a new-line.
> Nickel: Open an indent block between multi-line parentheses

- flake.nix
closes https://github.com/tweag/topiary/issues/405
This PR:
- fixes the bug described in #405 
- adds a flake check to avoid future similar breakages.
As an evidence that this works, I will push twice, once without the fix and once with it. The CI should complain about the first commit, and be happy with the second.
> Fix pre-commit-hook settings and add a flake check for them

- Cargo.lock
- topiary/Cargo.toml
- topiary/tests/sample-tester.rs
This new version uses `prettydif::text::diff_lines`, which is less generic than `pretty_assertions::assert_eq`, but was more easily modified, and suits our purpose well.
Currently, this is the output of a failed test with this PR:
I will edit https://github.com/romankoblov/prettydiff/pull/14 to add a skipping symbol (_e.g._ `[...]`) and line numbers.
Closes #401
> Reduce verbosity of failed tests

- topiary/src/atom_collection.rs
Resolves #346
Note: The flattening of the syntax tree can be factored out, to avoid having to do it twice (for single line breaks and blank lines). I will do this refactor in a separate PR.
> Rewrite detect_line_breaks_inner

- topiary/src/atom_collection.rs
> Further refactoring of topiary::atom_collection

- Cargo.lock
- topiary/Cargo.toml
Following the merge of my fix in `master` in https://github.com/romankoblov/prettydiff, we no longer need to tag it explicitly.
> Bump prettydiff version

- README.md
While installing Topiary, I found the explanation around `TOPIARY_LANGUAGE_DIR` in the README to a be a bit lacking (while it's an important point of the setup in order to make topiary correctly work with e.g. the Nickel language server)
- What this environment variable is and why we need it isn't completely covered. In particular, is it compulsory, and what happens if we don't set it.
- The text doesn't provide a sensible default/an example.
- The README says that `TOPIARY_LANGUAGE_DIR` can be set at build time as well, but I'm not sure what it means. I couldn't find (by grepping) and build script or build-time computation referring to this environment variable. My first understanding of this information would be that if you set it a build time, the topiary build somehow picks it up and …
> Expand on TOPIARY_LANGUAGE_DIR in the README

- languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
This PR corrects the formatting of trailing comments when they appear in the following contexts:
* After the truthy clause in an `if..then..else` expression.
* After the equals sign in a bound expression.
* After the delimiter in a compound value (e.g., list, record, etc.)
* After a the function/argument in a multi-line function call site.
There are some other contexts where trailing comments will be reflowed on to the following line. These have not been addressed because the trade-off with query complexity is too high.
Resolves #425
> Nickel: Correct formatting of trailing comments

- languages/nickel.scm
- topiary-playground/languages_export.ts
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
The comment exceptions from #431 were not quite right. This PR fixes the problem.
Resolves #439
> Nickel: Fix line breaking in container values which include a comment

- Cargo.lock
- languages/nickel.scm
- topiary-playground/languages_export.ts
- topiary/Cargo.toml
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
We decided to change the syntax for enum tags in Nickel from `` `Tag `` to `'Tag`. The newest unstable branch of the Nickel tree-sitter grammar supports that change. Additionally, it reflects the change of naming for some builtin types, namely `Str` became `String` and `Num` became `Number`.
None of these changes should affect the parse tree structure, ~so no queries should need changing.~ Well, that was a nice dream 😅
> Update tree-sitter-nickel to new unstable branch

- languages/ocaml.scm
- topiary-playground/languages_export.ts
- topiary/tests/samples/expected/ocaml.ml
- topiary/tests/samples/input/ocaml.ml
This solves the first example from #441 .
Generally speaking, all the hard lines are suspicious (in Ocaml in particular, but probably in every language), but I haven't t investigated further (I got hit by this one yesterday, so got incentivised to solve it; the playground is amazing for this sort of debugging by the way).
> Ocaml: modules can be on one line

- languages/ocaml.scm
- topiary-playground/languages_export.ts
- topiary/tests/samples/expected/ocaml.mli
Formats the following:
```ocaml
type ('a,'b,'c) x = (module R with type a = 'a and type b = 'b and
type c = 'c)
```
as
```ocaml
type ('a, 'b, 'c) x =
(
module R with
type a = 'a
and type b = 'b
and type c = 'c
)
```
Closes #450
> [OCaml] Support `package_type` in `type_binding`

- Cargo.toml
- MAINTAINERS.md
- topiary-cli/Cargo.toml
- topiary-playground/Cargo.toml
- topiary/Cargo.toml
Fixes #455. Related to #375.
Uses a workaround due to https://github.com/ipetkov/crane/issues/281#issuecomment-1560575302.
> Crate metadata plus workaround for Crane warning

- topiary/src/pretty.rs
This feels like tinkering, rather than a proper solution to #492, but it works for now.
Closes #492 
Closes #488
> Only trim line breaks in pretty-printing

- README.md
Thanks to @torhovland for reporting that this description was missing.
> Describe Topiary configuration in README.md

- .gitattributes
Topiary is considered by GitHub to be an OCaml project because our OCaml tests are rather substantial. I think it is best if we make it so GitHub identifies it as a Rust project for possible contributors.
> Linguist configuration to make Topiary a Rust project

- Cargo.lock
- Cargo.toml
- languages/ocaml.scm
This PR temporarily reverts the OCaml bump so we can investigate what is going on with it.
> Resolve #519 catastrophic performances on ocaml files

- topiary-cli/src/main.rs
- topiary-playground/src/lib.rs
- topiary/benches/benchmark.rs
- topiary/src/lib.rs
- topiary/src/tree_sitter.rs
- topiary/tests/sample-tester.rs
The query is then used between the formatting and the idempotence check. The TopiaryQuery struct helps keep the API clean.
```
format_ocaml            time:   [655.12 ms 658.89 ms 662.75 ms]
```
```
format_ocaml            time:   [430.05 ms 432.33 ms 434.68 ms]
change: [-34.911% -34.385% -33.879%] (p = 0.00 < 0.05)
```
> Create the query only once

- CHANGELOG.md
- README.md
- languages/ocaml.scm
- languages/rust.scm
- topiary/src/atom_collection.rs
- topiary/src/lib.rs
- topiary/src/pretty.rs
- topiary/src/tree_sitter.rs
- topiary/tests/samples/expected/bash.sh
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/expected/ocaml.ml
- topiary/tests/samples/expected/rust.rs
- topiary/tests/samples/expected/toml.toml
- topiary/tests/samples/expected/tree-sitter-query.scm
- topiary/tests/samples/input/bash.sh
- topiary/tests/samples/input/nickel.ncl
- topiary/tests/samples/input/ocaml.ml
- topiary/tests/samples/input/rust.rs
- topiary/tests/samples/input/toml.toml
- topiary/tests/samples/input/tree-sitter-query.scm
Fixes #111.
- Multi-line comment indenting.
- Documented new predicate, @multi_line_indent_all
Happily, the PR does not affect the benchmark.
> Indented leaves

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- languages/ocaml.scm
After #519 we reverted our update to tree-sitter-ocaml. Now that release 0.20.3 resolves the awful OCaml performance*, we can switch back to the latest official release.
* Topiary performance is still bad, but this is not inherent to OCaml
> Update tree-sitter-ocaml to 0.20.3 and reintroduce the new queries

- topiary/languages/ocaml.scm
> Fix: open scope "function_definition" more often

- CHANGELOG.md
- topiary-cli/src/error.rs
- topiary/src/error.rs
- topiary/src/lib.rs
Fixes #530.
- Improved error message when idempotency fails due to invalid output in the first pass.
> 530 idempotency parsing error message

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- MAINTAINERS.md
Fixes #415.
CI will automatically cut a release like this when pushing a new version tag.
> cargo-dist

- topiary/src/atom_collection.rs
> Fix handling of antispace in post-processing.

- topiary/languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
Mentioned in #547 but doesn't resolve all of it.
From #547:
> When parsing a `quoted_enum_tag`, `tree-sitter-nickel` defers to its scanner. The scanner produces a `quoted_enum_tag_start`, which is taken by Topiary and produced correctly. The parser then produces a `chunk_literal_single` containing only the contents of the following string. I.e. the last quote ending the string is completely dropped by `tree-sitter-nickel`.
> Fix Nickel quoted_enum_tag formatting by considering it a leaf

- topiary/languages/nickel.scm
- topiary/src/atom_collection.rs
This resolves part of #547, in particular the issue investigated by @torhovland.
```
[
a && (b & c | d),
a &&
(b & c | d),
a &&
(b &
c | d)
]
```
Get correctly formatted as:
```
[
a && (b & c | d),
a
&& (b & c | d),
a
&& (
b
& c | d
)
]
```
@torhovland's reasoning was correct, there was a scoping issue. The scope was started by the `[`, ending after the infix expression. Since the `[` was on a previous line, the entire expression was considered to be multi-line, and thus expanded as such. The scope was started there (and not on the next line) because that line was considered a `annotated_infix_expr` instead of an `infix_expr` which we did not include in our query to start the scope.
> Nickel: Start infix-chains also for annotated infix_expr

- topiary/languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
Done by starting a scope on the previous node instead of on the first annotation.This ensures that a single line annotation that was clearly put on a newline on purpose is actually formatted as such. This is the final PR in a series that fully resolves #547 (with the exception of the parsing error, which is currently being discussed in the Nickel team).
> Nickel: Resolve annotation idempotency

- README.md
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
> Remaining changes from Nickel idempotency issue

- topiary/languages/ocaml.scm
- topiary/tests/samples/expected/ocaml.ml
- topiary/tests/samples/input/ocaml.ml
> OCaml spacing error

- topiary-cli/src/main.rs
- topiary/src/tree_sitter.rs
> Fall back to compiled-in queries for supported languages.

- CHANGELOG.md
- README.md
- topiary/languages/nickel.scm
- topiary/languages/ocaml.scm
- topiary/languages/ocamllex.scm
- topiary/src/atom_collection.rs
- topiary/src/lib.rs
- topiary/tests/samples/expected/tree-sitter-query.scm
- topiary/tests/samples/input/tree-sitter-query.scm
Resolves #572 and unblocks #571
Creates atoms for the Scoping captures and introduces `prepend`/`append` versions of both `scope_begin` and `scope_end`.
> Create append/prepend versions of scope captures

- topiary/languages/nickel.scm
- topiary/tests/samples/expected/nickel.ncl
- topiary/tests/samples/input/nickel.ncl
Resolves #571 by only checking if the annotation itself started on a new line rather than the entire node before it.
> Append scope to node before annotation

- CHANGELOG.md
- README.md
- verify-documented-usage.sh
This forms a part of PR #583 and **must not** be merged into `main` alone. It is only the implementation of isolated functionality -- and thus not expected to necessarily pass the CI checks -- to split up the work into logical chunks.
**NOTE** This PR's code is mutually exclusive from that in #591 and #593, but the functionality in those PRs motivate the changes made here. It would therefore make sense to merge this one _after_ those have been approved and merged.
> CLI Changes Sub-PR: Documentation

- topiary-cli/src/configuration.rs
- topiary/src/configuration.rs
This forms a part of PR #583 and **must not** be merged into `main` alone. It is only the implementation of isolated functionality -- and thus not expected to necessarily pass the CI checks -- to split up the work into logical chunks.
**NOTE** Depends on #593.
> CLI Changes Sub-PR: TOML `merge` Collation

- Cargo.lock
- Cargo.toml
- README.md
- topiary-cli/Cargo.toml
- topiary-cli/src/error.rs
- topiary-cli/src/io.rs
- topiary-cli/src/language.rs
- topiary-cli/src/main.rs
- topiary/src/configuration.rs
- topiary/src/language.rs
This forms a part of PR #583 and **must not** be merged into `main` alone. It is only the implementation of isolated functionality -- and thus not expected to necessarily pass the CI checks -- to split up the work into logical chunks.
> CLI Changes Sub-PR: Formatting subcommand

- topiary/languages/toml.scm
- topiary/tests/samples/expected/toml.toml
- topiary/tests/samples/input/toml.toml
> toml: don't clobber quoted_key elements

- topiary/languages/toml.scm
- topiary/tests/samples/expected/toml.toml
- topiary/tests/samples/input/toml.toml
previously, if you had comments on individual items in a multiline
array, e.g.
```toml
children = [
"michael",
"gob", # i don't care too much for this one
"lindsay",
]
```
topiary would confusingly move the comment _below_ the element it was
placed next to-
```toml
children = [
"michael",
"gob",
"lindsay",
]
```
which can destroy the intent of the comment. this rule update now
preserves inline comments and won't insert a linebreak after a separator
if followed by one.
> toml: allow inline comments in multiline arrays

- topiary/languages/ocaml.scm
- topiary/tests/samples/expected/ocaml-interface.mli
- topiary/tests/samples/expected/ocaml.ml
- topiary/tests/samples/input/ocaml.ml
> [ocaml] Allow blank lines between recursive type definitions

- topiary/languages/toml.scm
- topiary/tests/samples/expected/toml.toml
- topiary/tests/samples/input/toml.toml
this is more a preference, but it comes from a learned (python)
annoyance- if you want to keep a set of things in sorted order, then
every time the last item changes you have to go in and pick around the
commas. in python it's a lot worse due to implicit string coercion,
this is thankfully just illegal in toml, but still feels a good move for
consistency and ease of sorting.
> toml: enforce final (oxford) comma in multiline arrays, remove from singleline arrays

- Cargo.lock
- Cargo.toml
- README.md
- default.nix
- topiary-cli/Cargo.toml
- topiary-cli/src/cli.rs
- topiary-cli/src/main.rs
- verify-documented-usage.sh
* Move to using full-form subcommands (e.g., `format` rather than `fmt`), for clarity. (The short-forms are still valid aliases).
* Added a shell completion generation subcommand.
> Full-form subcommands and completion

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Release 0.3.0, quite a big one this time.
> Release 0.3.0 Dreamy Dracaena

- topiary-queries/queries/ocaml.scm
- topiary/tests/samples/expected/ocaml-interface.mli
- topiary/tests/samples/expected/ocaml.ml
- topiary/tests/samples/input/ocaml.ml
- web-playground/package-lock.json
Closes #642
Closes #644
Closes #645
Closes #646
Closes #647
> Several OCaml fixes

- Cargo.lock
- Cargo.toml
Nickel's grammar was updated to correctly handle the curried dot operator (.) a few weeks ago, and ideally, I `nickel format` should be fixed for the upcoming 1.4 release, which requires Topiary to be updated to use the latest Nickel grammar.
> Update tree-sitter-nickel to latest grammar

- Cargo.toml
- topiary-cli/Cargo.toml
- topiary-cli/tests/samples/expected/toml.toml
- topiary-core/languages.toml
- topiary-playground/Cargo.toml
- topiary-queries/queries/toml.scm
- topiary-web-tree-sitter-sys/Cargo.toml
This PR adds a small modification to the `toml.scm` query file, and uses it to format our own `.toml` files, in the spirit of dogfooding.
> TOML fixes + formatting our own files

- .github/workflows/ci.yml
- update-wasm-grammars.sh
The problem was that the frontend's NPM modules were being cached incorrectly: this included Puppeteer, so it wasn't reinstalled, but _didn't_ include Puppeteer's Chrome. Updated the cache to include Puppeteer's Chrome.
(Also updated the `update-wasm-grammars.sh` script to generate the Bash Tree-sitter WASM.)
Resolves #665
> Fix playground CI test problem

- topiary-cli/tests/samples/expected/nickel.ncl
- topiary-cli/tests/samples/input/nickel.ncl
- topiary-queries/queries/nickel.scm
> Nickel: Don't prepend line break to equals signs in annotations

- Cargo.lock
- Cargo.toml
- default.nix
- flake.lock
- topiary-tree-sitter-facade/src/node.rs
* Updated to Rust 1.74, to maintain compatibility with newer dependencies
* Pinned Tree-sitter to 0.20.10 and forced `tree-sitter-json` to the same to maintain API compatibility amongst all grammars
* Pinned `tree-sitter-rust` to a known working rev
* Pinned `tree-sitter-nickel` to rev with C-based scanner
* Update `wasm-bindgen` to 0.2.91 (I'm not sure why this is needed, but it won't build without :shrug:)
* Fixed `PartialOrd` implementation in the Tree-sitter facade
> Dependency updates and fixes

- README.md
This PR updates the readme's installation instructions to reference the `queries` directory nested under the `topiary-queries` crate. This is consistent with the example `export TOPIARY_LANGUAGE_DIR` command that appears soon after.
> README.md: improve install instructions

- flake.nix
Thanks Nickel team for the inpiration: https://github.com/tweag/nickel/blob/6e79f0db56d7a66b70a3f7c6521ab4c4a286e89d/flake.nix#L84
This should avoid problems in the future when we update wasm-bindgen.
Resolves #686
> chore: override wasm-bindgen-cli with the version from the Cargo.lock

- Cargo.lock
- Cargo.toml
- flake.lock
This PR pins all our grammar crates to avoid the duplicate tree-sitter issues.
It also updates the flake inputs to get access to a newer rustc version.
> fix: pin our grammar crates; update flake inputs

- CHANGELOG.md
- topiary-cli/src/error.rs
- topiary-core/src/tree_sitter.rs
Issue: #681
This is part one of issue #681, adding the row and column to the debug output while not supporting named patterns yet.
> Output the (column, row) of a patternmatch when outputing at the INFO level

- topiary-core/src/atom_collection.rs
The previous solution was needlessly recursive, this version changes the recursion into a loop.
- ~[ ] CHANGELOG.md updated~
- ~[ ] README.md up-to-date~
> fix: remove first/last_leaf_inner

- Cargo.lock
- Cargo.toml
Prepare a release of `topiary-queries` with the latest Nickel queries to `crates.io`. For the time being, it was decided that it's ok to bump the patch version for such an update. I hesitated to do this just for `topiary-queries`, but that would mean to stop using the workspace version for `topiary-queries`, but the added risk of being out of sync (or to just forget to bump `topiary-queries`'s version during an update) isn't worth it IMHO. Instead, I think we should just accept to bump the whole workspace version.
I don't know if a GitHub release is very useful to do in this case (or a cargo release of other Topiary crates). I think it's fine to keep all the others crates at `0.4.0` on GitHub and crates.io until the next update, and just publish `topiary-queries`. But I'm happy to do …
> Bump version to 0.4.1

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/client-app/Cargo.toml
- topiary-cli/Cargo.toml
- topiary-cli/src/io.rs
- topiary-cli/tests/cli-tester.rs
- topiary-cli/tests/sample-tester.rs
- topiary-config/Cargo.toml
- topiary-config/src/serde.rs
- topiary-playground/Cargo.toml
- topiary-queries/Cargo.toml
Resolves #710
Put each grammar and its associated dependencies behind a feature gate. By default, the supported and contributed languages will be built; experimental languages (Bash and Rust) will not.
> Feature Gate Grammars

- topiary-cli/tests/samples/expected/ocaml.ml
- topiary-cli/tests/samples/input/ocaml.ml
- topiary-queries/queries/ocaml.scm
Issue: #719
This fixes the formatting of pattern matching of constructors with an inline record pattern, which previously was missing a space.
> fix: missing space for pattern matching of constructor holding record

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- topiary-cli/tests/samples/expected/nickel.ncl
- topiary-cli/tests/samples/input/nickel.ncl
- topiary-queries/queries/nickel.scm
Apply the new formatting proposal detailed in https://github.com/tweag/nickel/issues/2003 for function application and parenthesized expressions in Nickel, to reduce the inflation of indentation when using higher-order functions (and more specifically contract constructors such as `std.contract.from_predicate` or `std.contract.custom`).
This PR required to change a bit the logic of the rules applying to function applications and the like. I was helped by @nbacquey through a pairing session; thanks again for your help!
This commit also bumps the patch version of the workspace to prepare for the corresponding release of topiary-queries so that it can be published and use from the nickel-* crates.
In addition to regression tests, this PR also updates the Nickel stdlib sample to the latest …
> Update formatting of function application and parenthesized blocks in Nickel

- topiary-config/src/language.rs
Issue: #740 
We manually created ~/.cache/topiary and ~/.cache/topiary/language. By using `create_dir_all` we can guarantee that all parent directories are also created.
> fix: use create_dir_all to also create .cache and other dirs

- CHANGELOG.md
- topiary-cli/tests/samples/expected/ocaml.ml
- topiary-cli/tests/samples/input/ocaml.ml
- topiary-queries/queries/ocaml.scm
Formats the following as is:
```ocaml
let foo
(bar :
int ->
string ->
unit
)
~(baz :
int ->
string ->
unit
)
=
bar baz
```
Closes #727
> Format typed patterns in function arguments

- CHANGELOG.md
- topiary-cli/tests/samples/expected/ocaml.ml
- topiary-cli/tests/samples/input/ocaml.ml
- topiary-queries/queries/ocaml.scm
Allows the following to be formatted as is:
```ocaml
foo
bar
(fun baz ->
baaaaaaz
)
(fun qux ->
quuuuuux
)
```
This is a kind of a setback regarding the formatting of snippets such as the following:
```ocaml
foo bar (fun x ->
x
)
```
But I believe the topiary language isn't sufficiently expressive to currently have both.
Closes #726
> Indentation on multi-line call containing functions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- bin/verify-documented-usage.sh
- topiary-cli/src/cli.rs
- topiary-cli/src/error.rs
- topiary-cli/src/main.rs
- topiary-config/Cargo.toml
- topiary-config/src/error.rs
- topiary-config/src/language.rs
- topiary-config/src/lib.rs
- topiary-config/src/source.rs
With the dynamic loading PR landing recently, it made sense to have a subcommand that prefetches and compiles all grammars in the configuration.
> feat: add prefetch subcommand

- CHANGELOG.md
- topiary-cli/tests/samples/expected/nickel.ncl
- topiary-cli/tests/samples/input/nickel.ncl
- topiary-queries/queries/nickel.scm
Closes #743
This is a tentative fix of #743, but I have yet to figure out how to properly handle the indentation part.
> Fix Nickel inconsistent formatting of annotated let-bindings

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- topiary-config/Cargo.toml
- topiary-config/src/language.rs
- topiary-core/Cargo.toml
- topiary-core/src/lib.rs
- topiary-core/src/tree_sitter.rs
- topiary-tree-sitter-facade/Cargo.toml
- topiary-tree-sitter-facade/src/language.rs
- topiary-tree-sitter-facade/src/parser.rs
- topiary-tree-sitter-facade/src/query.rs
- topiary-tree-sitter-facade/src/query_match.rs
Closes #684 
Biggest difficulty is that `tree_sitter::QueryMatches` is now a `StreamingIterator`, returning references rather than values. This makes it very difficult to store in a new type.
Instead make `topiary_tree_sitter_facade::QueryMatch` a trait rather than a new type. This seems to be the easiest way to preserve as much of the existing structure as possible.
Not tested for the wasm32 build, so possibly some changes required there to match.
> Bump tree-sitter to 0.24 (not a release)

- .github/workflows/ci.yml
- topiary-core/benches/benchmark.rs
- topiary-core/src/tree_sitter.rs
- topiary-tree-sitter-facade/src/query.rs
- topiary-tree-sitter-facade/src/query_match.rs
- topiary-web-tree-sitter-sys/src/lib.rs
Also updated benchmark to use new `tree-sitter-ocaml` API.
> Trigger CI on PR, as well as push

- default.nix
- flake.nix
This makes topiary easier to use from Nix… you can now use `nix run`
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.
> provide & use mainProgram

- Cargo.toml
Since the introduction of Nickel as the configuration language for Topiary, the build time from scratch has taken a big hit. It turns out we had build time issues in Nickel as well some time ago, and it was due to LALRPOP: the latter does quite a bit of work at build time to generate the parser, but by default cargo builds `build-dependencies` without optimizations, in order to optimize for compilation time. However, in this case, the optimum is actually to aggressively optimize LARLPOP at build time.
We got good results by changing the configuration in Nickel's `Cargo.toml`. Unfortunately, as noted in https://github.com/tweag/nickel/issues/2123, this setting doesn't propagate to downstream dependencies. I don't have a nice solution for now, but a temporary one is just to reproduce the …
> Optimize LALRPOP compilation to reduce build time

- README.md
the current `README.md` has an example that referred to an old variant of starting scopes
> fix(docs): fix outdated example that uses `@begin_scope` tag

- CHANGELOG.md
- topiary-cli/tests/samples/expected/tree_sitter_query.scm
- topiary-cli/tests/samples/input/tree_sitter_query.scm
- topiary-queries/queries/tree_sitter_query.scm
* prevent invalid formatting of `field_definition` that followed an `identifier`
```scm
(function_call function: (identifier) @function)
```
Currently the line above would format to the invalid output below:
```scm
(function_callfunction: (identifier) @function)
```
* `predicates` parameters are now separated by a `spaced_softline` allowing long predicates to be broken up
```scm
(
(identifier) @function.builtin
(#any-of?
@function.builtin
"union"
"difference"
"intersection"
"circle"
"square"
"polygon"
"text"
"import"
"projection"
"sphere"
"cube"
"cylinder"
"polyhedron"
"linear_extrude"
"rotate_extrude"
"surface"
"translate"
"rotate"
"scale"
"resize"
"mirror"
"multmatrix"
"color"
"offset"
"hull"
"minkowski")
)
```
Currently the code would be formatted into a very long predicate line: …
> fix(topiary-queries/scm): Fixed invalid formatting of `field_definition`s 

- CHANGELOG.md
- Cargo.toml
- README.md
- default.nix
- topiary-cli/src/io.rs
- topiary-cli/tests/samples/expected/nickel.ncl
- topiary-cli/tests/samples/expected/ocaml-interface.mli
- topiary-cli/tests/samples/expected/tree_sitter_query.scm
- topiary-cli/tests/samples/input/nickel.ncl
- topiary-cli/tests/samples/input/ocaml-interface.mli
- topiary-cli/tests/samples/input/tree_sitter_query.scm
- topiary-config/src/language.rs
- topiary-config/src/source.rs
- topiary-core/src/atom_collection.rs
- topiary-core/src/language.rs
- topiary-core/src/lib.rs
- topiary-core/src/pretty.rs
- topiary-core/src/tree_sitter.rs
- topiary-queries/queries/nickel.scm
- topiary-queries/queries/ocamllex.scm
- typos.toml
- web-playground/src/App.tsx
* Ran [`typos -w`](https://github.com/crate-ci/typos) on the project 
* Added `typos.toml` config file
> chore(lint): run `typos-cli` on project

- CHANGELOG.md
- README.md
- topiary-cli/Cargo.toml
- topiary-config/Cargo.toml
- topiary-core/src/atom_collection.rs
- topiary-core/src/lib.rs
- topiary-core/src/pretty.rs
Issue: #836 
This adds really basic support for the feature discussed in the linked issue.
I tested it with my SQL capture, and it works, but I don't know if adding SQL as a language is in scope for this PR and there are a lot of other issues with my query (it's still kinda ugly).
> Add support for @upper_case @lower_case captures

- topiary-cli/src/io.rs
- topiary-core/benches/benchmark.rs
- topiary-core/src/tree_sitter.rs
- topiary-tree-sitter-facade/src/language.rs
- topiary-tree-sitter-facade/src/node.rs
- topiary-tree-sitter-facade/src/query_capture.rs
- topiary-tree-sitter-facade/src/query_predicate.rs
- topiary-tree-sitter-facade/src/tree_cursor.rs
https://github.com/tweag/topiary/pull/845 [CI run](https://github.com/tweag/topiary/actions/runs/12917298008/job/36023363227?pr=845) complained about unelided lifetimes, ran `cargo clippy --fix` to solve the issue.
> fix(clippy): apply `needless_lifetimes` clippy fix

- README.md
Resolves #840
Resolves #841
Fixes an observed regression in the `README` from #354. The offending PR couldn't be found and `git blame` wasn't helpful. This is slightly annoying as it leaves some room for doubt over other potential divergence.
I did find one other copy-and-paste fail, for the TTY playground.
I also took the opportunity to document `@leaf` and the considerations around query and capture order.
> Fix and update `README`

- CHANGELOG.md
- README.md
- topiary-cli/src/cli.rs
- topiary-cli/src/fs.rs
- topiary-cli/src/main.rs
Resolves #834
Provides an `-L`/`--follow-symlinks` option to `topiary format` which will follow and resolve symlinks when computing the set of input files. If this CLI option is specified, then the filesystem traversal:
* Can "break out" of the specified directories by following any directory symlinks elsewhere.
* Will resolve symlinked files to their canonical path (skipping, if the link is broken).
The deduplication now happens after the traversal, rather than before, to dedup symlinks that point to files that exist within the input file set. (This means that if you do, say, `topiary format directory directory`, then it will do twice as much work before dedup'ing, but that's an edge case that's not worth worrying about.)
> Optionally follow symlinks when specifying input files

- CHANGELOG.md
- topiary-cli/src/io.rs
- topiary-config/src/source.rs
Resolves #823
Resolves #825
Resolves #843
* Don't panic with info (or higher) logging when using process substitution to provide configuration.
* Sensible logging of configuration sources.
* Clean-up temporary files on process interruption.
> Various small fixes

- .github/workflows/release.yml
- Cargo.toml
Updates `cargo-dist` to v0.28 to access the current GitHub runners. Using the `latest` release doesn't work, because the version needs to be specified in `Cargo.toml`.
> [!NOTE]
> I have not been able to get prereleases to work, so this is untested. https://github.com/axodotdev/cargo-dist/issues/1707 suggests that bumping the version will resolve the problem we had, but the only way of checking (for now) is to push a `v0.6.0` tag -- once this PR is merged -- and hope for the best.
> 
> If it doesn't work, then I'll delete the `v0.6.0` tag as quickly as possible and go back to the drawing board. (See also #856 for tracking a long-term fix to this problem.)
> Update `cargo-dist` to v0.28 to access current GitHub runners

- Cargo.lock
- Cargo.toml
- flake.nix
Latest nixpkgs-unstable doesn't package wasm-bindgen 0.2.91 anymore. It's still possible to use via overrides, but bumping the version to one that's explicitly packaged should let us hit the binary cache more often.
There are also more changes needed next time nixpkgs is updated: we'll need to either depend on a package like `wasm-bindgen-cli_0_2_100` or do something like
```nix
wasm-bindgen-cli = pkgs.buildWasmBindgenCli rec {
src = pkgs.fetchCrate {
pname = "wasm-bindgen-cli";
version = wasmBindgenVersion;
hash = "sha256-f/RK6s12ItqKJWJlA2WtOXtwX4Y0qa8bq/JHlLTAS3c=";
};
cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
inherit src;
inherit (src) pname version;
hash = "sha256-F97UDB2WV1AgaDWpptgumYo2VeiYgXuBZzw+wmCHUcE=";
};
};
```
> Bump wasm-bindgen to 2.100

- topiary-tree-sitter-facade/src/language.rs
#794 replaced a `From<tree_sitter::Language>` implementation with a `From<tree_sitter_language::LanguageFn>` implementation. But I see no reason we can't have both, so this PR re-instates the former.
> Support converting from tree_sitter::Language

- .github/workflows/ci.yml
- CHANGELOG.md
- topiary-config/src/lib.rs
References #868
For reasons, the MSVC linker does not like building multiple grammars concurrently and it hits a race condition :shrug: It's not at all clear why this happens, so the best we can do for the time being is stick a plaster over the problem: No concurrent grammar builds on Windows.
> Investigate and fix parallel grammar builds on Windows

- flake.lock
- flake.nix
This PR updates `flake.lock`. It also takes inspiration from a recent update on Nickel, where we could get rid of the more fragile `override` and use a Nixpkgs-provided helper instead to get a `wasm-bindgen-cli` with a fixed version.
By the way, should Topiary set up a `update-flake-lock` git-hub action, to make sure Nix dependencies get updated frequently and automatically?
This change doesn't need to be mentioned in the changelog.
> Update flake lock, use buildWasmBindgenCli instead of override

- .github/workflows/update-flake-lock.yml
This PR adds a workflow to automatically update flake.lock weekly. In order to work , we need to add some maintainer's Personal Access Token to the secrets of this repository, under `GH_TOKEN_FOR_UPDATES`. See the link in the in the workflow.
> Add update-flake-lock workflow

- .gitattributes
The Nix flake update action [failed](https://github.com/tweag/topiary/actions/runs/13477909315/job/37659368819). It failed because, when the repository is checked out, a bunch of binary files (`*.png` and `*.wasm`) are checked out in a weird state.
This PR is a (naive) attempt to fix that: We set PNG and WASM files to be `binary` in `.gitattributes` to ensure they are not considered as text :crossed_fingers:
(No changes needed to docs)
> Attempt: Correct checkout for Nix flake updater to run

- docs/book/src/SUMMARY.md
- docs/book/src/playground/tty.md
- docs/book/src/playground/web.md
Short documentation for the Topiary web playground, including mentioning its current development state (or lack thereof).
> Topiary Book: Documentation for the web playground

- .cargo/audit.toml
Resolves #902 
Add `RUSTSEC-2024-0436` (`paste` unmaintained) to whitelist.
> Ignore RUSTSEC-2024-0436

- CHANGELOG.md
- flake.lock
- flake.nix
- topiary-config/languages.ncl
References https://github.com/Leathong/openscad-LSP/issues/35
tree-sitter-openscad has moved to the https://github.com/openscad org where the NPM package, crate, and python lib are pushed from. This PR updates the grammar location in `languages.ncl` and `flake.nix` to point to https://github.com/openscad/tree-sitter-openscad/
> chore: Use official grammar repo for OpenSCAD

- CHANGELOG.md
- topiary-cli/tests/samples/expected/ocaml.ml
- topiary-cli/tests/samples/expected/ocaml_interface.mli
- topiary-cli/tests/samples/input/ocaml.ml
- topiary-config/languages.ncl
- topiary-queries/queries/ocaml.scm
Closes #882 
Closes #904 
The initial goal of this PR was just to fix #882, but in the process of updating the tree-sitter grammar, #904 became apparent. So this PR fixes both.
> Update tree-sitter OCaml grammar and fix ensuing issues

- .github/workflows/ci.yml
- .github/workflows/website.yaml
- default.nix
- docs/book/book.toml
- flake.nix
- website/index.html
* Created a Nix output for the Topiary Book.
* Updated the website landing page to link to the book (and a few other misc updates).
* Remove the website building steps from `ci.yml`, replacing them with a dedicated `website.yaml` workflow, which:
* Builds the playground specifically from the `playground` branch, while it is out of maintenance; with better caching to reduce build times (as it's not likely to change).
* Builds the website as before, minus the end-to-end testing, but including building and incorporating the Topiary Book.
* Deploys (as before).
> Topiary book: Publish book to Topiary website

- website/index.html
It was pointed out on Discord that the "All rights reserved" text in the website's footer is at odds with the MIT licence that applies to the rest of the repo. Moreover, it appears as though the use of this phrase is [obsolete](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence) nowadays.
> Remove "All rights reserved" from website footer

- CHANGELOG.md
- docs/book/src/cli/usage/index.md
- docs/book/src/cli/usage/prefetch.md
- topiary-cli/src/cli.rs
- topiary-cli/src/main.rs
- topiary-config/src/lib.rs
Resolves #895
Creates a simplified version of the `prefetch_languages` function that looks up a specific language and prefetches it. The tempdir creation can be abstracted, but I don't think it's worth it with it being only 2 lines of code.
> feat(config): add support for prefetching a single language

- .github/workflows/website.yaml
- web-playground/package-lock.json
- web-playground/package.json
References https://github.com/tweag/topiary/actions/runs/15021035725/job/42210039730
The web playground's package manifest had become so outdated that it was failing and causing the respective GitHub action to timeout. This PR is a naive attempt to update all the packages to something more current:
```console
$ npx npm-check-updates --upgrade
$ git rm web-playground/package-lock.json
$ npm install --prefix web-playground --package-lock-only
```
> Fix Puppeteer deprecation

- docs/book/src/reference/capture-names/vertical-spacing.md
References #993
Documented @nbacquey's tip to insert blank lines between nodes in the Topiary Book.
> Document tip for inserting blank lines between nodes

- docs/book/src/reference/capture-names/vertical-spacing.md
References #1008
References #1001
References #993
Add a note to the `\n\n`-delimiter tip regarding its opacity to the run-of-whitespace post-processing step.
(Also moved the tip out of the example for `@{append,prepend}_hardline`.)
> Expand blank line tip in Topiary Book

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- MAINTAINERS.md
- flake.lock
Cutting a full release so we can move to Tree-sitter 0.25 and unblock downstream projects.
Also documented the new interim release process for configuration and queries.
> Release 0.6.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- topiary-cli/tests/samples/expected/bash.sh
- topiary-queries/Cargo.toml
- topiary-queries/queries/bash.scm
Resolves #995
Converting POSIX `[`-style test brackets to Bash's `[[` was a controversial choice. The discussion in #995 has convinced me to rescind this rewrite. The other Bash rewrites remain, as they don't change semantics except in _very_ niche edge cases.
> Bash: Don't rewrite `[` to `[[`

- MAINTAINERS.md
See #1011
See #1015
Updated the maintainer guidance on interim versions of `topiary-{config,queries}`. The `-YYYYMMDD` suffix proved to be unworkable, so we decided to decouple these and allow them to diverge.
> Updated versioning scheme for `topiary-{config,queries}`

- docs/book/src/reference/capture-names/vertical-spacing.md
Resolves #1048
Explicitly explain that nodes marked with a softline capture are determined to be multiline by virtue of the multilineness of their immediate parent. Also made scope analogue.
> Clarification of how multilineness is determined for softlines

- Cargo.lock
- Cargo.toml
- topiary-config/languages.ncl
This bumps tree-sitter-nickel, fixing a couple of small bugs. There are some small changes to the grammar (some `field_def`s will now be wrapped in a `field_decl`), but there don't appear to be any required changes in topiary.
> Bump tree-sitter-nickel to 0.5.0

- CHANGELOG.md
- topiary-cli/src/main.rs
Certain errors would not get logged during an early return because they exited the async block rather than the let scope:
https://github.com/tweag/topiary/blob/5f336358fe2ccc9a0a9c2b52b38d60df67f41cf8/topiary-cli/src/main.rs#L62-L63
This resulted in only the match arm below being logged:
https://github.com/tweag/topiary/blob/5f336358fe2ccc9a0a9c2b52b38d60df67f41cf8/topiary-cli/src/main.rs#L102-L104
This PR changes the scoped future to log all errors emitted.
> fix(cli): log early returns during formatting

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- flake.lock
- nix/packages/topiary.nix
- topiary-cli/tests/samples/expected/css.css
- topiary-cli/tests/samples/input/css.css
- topiary-config/Cargo.toml
- topiary-config/languages.ncl
- topiary-queries/Cargo.toml
- topiary-queries/queries/css.scm
Resolves #1083
Resolves #1084
CC @lavigneer
CSS fixes:
- Comments after declarations
- Identifiers that include special characters
> CSS formatting fixes
