tweag/topiary

README.md

A comment to explain the example I had a hard time to understand.

Comment on @do_nothing with starred regexp

---

src/atom_collection.rs

This new `post_process` function only goes once through the vector of atoms in the `AtomCollection`.

Rework postprocess

---

.editorconfig
default.nix
src/main.rs

this introduces the environment varialbe  `TOPIARY_LANGUAGE_DIR` at build time and allows running topiary outside of the directory
this will make it easier to be packaged in nixpkgs and also allows `nix run`ing without cloning the repository

bundle the language directory

---

.github/workflows/ci.yml
flake.nix

chore: rename cachix cache (tweag/infra#291)

---

README.md

Updated README with new CLI usage instructions.
(Apologies: This should have been part of #115)

Documented language selection

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Adds the "nonrec" keyword where it was missing.

Handle nonrec types

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

This adds the "+=" symbol and all spaces in several kind of type applications where it was missing.

Support for extensible variants and spaces in all the kind of type applications.

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Add "for", "to" and "while" keywords, as well as indentation related to "do" and "done".

Handle for and while loops

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Handle mutually recursive types

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Add some support for ppx language extensions.

Ppx extension

---

languages/ocaml.scm

This seems to solve the issue mentioned in #162

[Ocaml] Add an anchor for performance

---

languages/bash.scm
tests/samples/expected/bash.sh
tests/samples/input/bash.sh

This PR introduces support for basic Bash commands and conditional blocks, with appropriate samples for integration testing. This is in aid of #138.

[Bash] Step 1: Basic commands and conditionals

---

src/language.rs

Check env variable for language directory at runtime

---

src/main.rs

Open output file in write mode

---

Cargo.lock
Cargo.toml
languages/nickel.scm
src/language.rs
tests/samples/expected/nickel.ncl
tests/samples/input/nickel.ncl

This is a very drafty version of the formatter for Nickel.
The main purpose of it is to have people complaining about the output to know what the formatter should do.
The current version tends to add new lines and spaces quite often (and is not always super consistent about spaces).

Draft Nickel formatter

---

languages/bash.scm
tests/samples/expected/bash.sh
tests/samples/input/bash.sh

This PR introduces:
Notes
* Resolves #138

[Bash] Comments

---

README.md

Document usage of TOPIARY_LANGUAGE_DIR

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Resolves #232, modulo OCaml people's approval

Surround :: with spaces in all instances

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/expected/ocaml.mli
tests/samples/input/ocaml.ml

[OCaml] fix softlines and indentation in type definitions

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

[OCaml] fix hash type spacing

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

[OCaml] Duplicate record declaration logic for record expressions

---

languages/ocaml.scm
tests/samples/expected/ocaml.ml
tests/samples/input/ocaml.ml

Fixes double bracketing and update comment in the sample file.

[OCaml] Fixup after #280

---

README.md

This PR:
**I will defer merging until this has at least two approvals :heavy_check_mark:**

Prepare documentation for v0.1 release

---

src/atom_collection.rs

This PR decreases the processing time of the larger OCaml files from ~12s to ~7s.
Closes #312

[perf] pre-compute `parent_leaf_node` values

---

Cargo.lock
Cargo.toml
flake.lock
src/bin/topiary/main.rs

This PR updates clap to v4.1 and fixes breaking changes from v3.2
Resolves #322

Update clap to v4.1

---

.vscode/launch.json
Cargo.lock
Cargo.toml
flake.lock
src/atom_collection.rs
src/configuration.rs
src/error.rs
src/language.rs
src/lib.rs
src/tree_sitter.rs

First step on the way to implementing #171.

Use tree-sitter-facade to enable Wasm support

---

CONTRIBUTING.md
README.md
playground.sh

Update paths to test files

---

topiary/src/atom_collection.rs
topiary/src/error.rs
topiary/src/lib.rs
topiary/tests/samples/input/nickel2.ncl

I'm happy to discuss the individual changes here, and whether or not they are improvements.

More in-place processing and less cloning.

---

languages/nickel.scm
topiary/tests/samples/expected/nickel.ncl

Nickel: else..if chains

---

languages/nickel.scm
topiary/tests/samples/expected/nickel.ncl

Nickel: Multi-line applicative chains

---

topiary/src/atom_collection.rs

Per https://github.com/tweag/topiary/pull/411#issuecomment-1494705189

Downgrade zero-width output to debug

---

languages/nickel.scm
languages/tree-sitter-query.scm
playground.sh
topiary/tests/samples/expected/nickel.ncl

Resolves #422 
(Also resolves #389 "accidentally")

Nickel: Consistent formatting for bound expressions

---

languages/nickel.scm
topiary/tests/samples/expected/nickel.ncl
topiary/tests/samples/input/nickel.ncl

Match Nickel brace spacing with preferences

---

Cargo.toml
default.nix

Add missing package names and versions

---

languages/ocaml.scm
topiary-playground/languages_export.ts
topiary/src/atom_collection.rs
topiary/tests/samples/expected/ocaml.ml
topiary/tests/samples/input/ocaml.ml

* Add support for `initializer` keyword
* Fix post-processing of `DeleteBegin`/`DeleteEnd` sections
Closes #441

Fix idempotency issues in OCaml

---

CHANGELOG.md
MAINTAINERS.md

This PR prepares the v0.2.0 release.

Update CHANGELOG for v0.2.0

---

topiary-playground/src/lib.rs
web-playground/e2e/sample-tester.test.ts
web-playground/src/App.tsx

This PR fixes end-to-end tests for the playground, and fixes a leftover bug preventing tree-sitter queries for being correctly formatted

Fix e2e tests 

---

web-playground/package-lock.json
web-playground/package.json

Not having any luck in getting Puppeteer > v18 working on GitHub Actions. A similar issue is discussed here:
https://github.com/puppeteer/puppeteer/issues/9128#issuecomment-1458307585

Downgrade Puppeteer

---

web-playground/e2e/sample-tester.test.ts
web-playground/src/App.tsx

Ask for user confirmation if changing language overwrites modifications

---

CONTRIBUTING.md
Cargo.lock
topiary-cli/src/error.rs
topiary-cli/src/supported.rs
topiary-playground/build.rs
topiary/benches/benchmark.rs
topiary/src/atom_collection.rs
topiary/src/configuration.rs
topiary/src/error.rs
topiary/src/graphviz.rs
topiary/src/language.rs
topiary/src/lib.rs
topiary/src/pretty.rs
topiary/src/tree_sitter.rs
topiary/tests/sample-tester.rs

Minor improvements as suggested by `cargo clippy --all-targets --all-features -- -W clippy::pedantic`.

Clippy pedantic

---

.github/workflows/ci.yml
README.md
verify-documented-usage.sh

Verify that usage in README.md matches CLI output

---

topiary/src/tree_sitter.rs

Fix SIGSEGV error in exhaustivity testing

---

web-playground/src/App.css
web-playground/src/App.tsx

Show processing time in playground

---

topiary-playground/src/lib.rs
web-playground/src/App.tsx

Configurable idempotency check

---

web-playground/e2e/sample-tester.test.ts

These changes are necessary for the tests to work on my Fedora machine. Why it works on CI is a mystery.

Make the Puppeteer tests more robust.

---

Cargo.lock
Cargo.toml
languages/ocaml.scm

Uses the `infix_operator` refactor of [v0.20.2](https://github.com/tree-sitter/tree-sitter-ocaml/releases/tag/v0.20.2).

[OCaml] Bump tree-sitter grammar version

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Resolves #501
For this release I tried to make the changelog a little more user-friendly, although further refinement is needed.

Prepare release 0.2.2

---

.github/workflows/ci.yml
README.md
topiary-cli/src/main.rs
topiary-playground/src/lib.rs
topiary/benches/benchmark.rs
topiary/src/atom_collection.rs
topiary/src/lib.rs
topiary/src/test_utils.rs
topiary/src/tree_sitter.rs
topiary/tests/sample-tester.rs
web-playground/src/App.tsx

Fixes #363.
- Option for tolerating parse errors.
- Tolerate parse errors in playground.

Loose mode for tolerating parsing errors

---

CONTRIBUTING.md

More details about how to update Wasm grammars.

---

topiary/src/atom_collection.rs
topiary/src/configuration.rs
topiary/src/error.rs
topiary/src/graphviz.rs
topiary/src/language.rs
topiary/src/lib.rs
topiary/src/pretty.rs
topiary/src/tree_sitter.rs

Document most of the Topiary library's public and private symbols

---

.github/workflows/ci.yml

https://github.com/cachix/install-nix-action/issues/183

macos-latest should be working again.

---

topiary/languages/tree-sitter-query.scm

Append a space to every individual predicate parameter

---

website/index.html
website/styles/topiary.css

Add [GitHub corner](https://github.com/tholman/github-corners):
Resolves #559

Added GitHub link to website

---

web-playground/src/App.tsx
web-playground/src/components/editor.tsx

Scheme highlighting on query in playground.

---

flake.nix
playground.sh

This forms a part of PR #583 and **must not** be merged into `main` alone. It is only the implementation of isolated functionality -- and thus not expected to necessarily pass the CI checks -- to split up the work into logical chunks.

CLI Changes Sub-PR: Update supplementary tools

---

.envrc
.gitignore
default.nix
flake.nix
shell.nix

Also reworks the way we call `default.nix` a little bit.

Adds an explicit devShell to our flake

---

README.md
topiary-cli/src/cli.rs
topiary-cli/src/main.rs

Resolves #603
:bulb: This depends on #601

Expose the logging level via the command line

---

topiary-cli/Cargo.toml
topiary-cli/src/cli.rs
topiary-cli/src/error.rs
topiary-cli/src/language.rs
topiary-cli/src/main.rs

Resolves #605 
:bulb: This depends on #607

Fix language definition cache locking

---

topiary/languages/ocaml.scm
topiary/tests/samples/expected/ocaml.ml
topiary/tests/samples/input/ocaml.ml

[ocaml] local opens format the same as prenthesized expressions

---

topiary/languages/ocaml.scm
topiary/tests/samples/expected/ocaml.ml
topiary/tests/samples/input/ocaml.ml

[ocaml] proper line breaks in `or_pattern`

---

web-playground/package-lock.json
web-playground/package.json
web-playground/src/App.tsx
web-playground/src/components/editor.tsx

Syntax highlighting for all languages except Nickel.

---

topiary/src/atom_collection.rs
topiary/src/tree_sitter.rs

Changes logs to use 1-based source positions by adding a `NodeExt` trait and a `Display` impl to `LocalQueryMatch`.
Closes https://github.com/tweag/topiary/issues/548, unless I've missed something.

Make source positions in logs 1-based for consistency

---

topiary-cli/tests/samples/expected/ocaml.ml
topiary-cli/tests/samples/input/ocaml.ml
topiary-queries/queries/ocaml.scm

[ocaml] handle the `;;` separator

---

.github/pull_request_template.md

Hopefully, this will ensure that we always have an up to date CHANGELOG.md file.

chore: include pr template

---

bin/update-wasm-grammars.sh

Cherry-picked from #705, to separate concerns.
- ~[ ] CHANGELOG.md updated~
- ~[ ] README.md up-to-date~

Update WASM generation script

---

bin/playground.sh

* Correct mapping from language to default query
* Correct mapping from language to sample input
* Use the appropriate feature flag for the language
> [!NOTE]
> This has been cherry-picked from #713.
- ~[ ] CHANGELOG.md updated~
- ~[ ] README.md up-to-date~

TTY playground: Small fixes and use the feature gates

---

topiary-core/Cargo.toml

Move `tokio-test` to dev-dependencies

---

CHANGELOG.md
topiary-cli/tests/samples/expected/bash.sh
topiary-cli/tests/samples/input/bash.sh
topiary-queries/queries/bash.scm
topiary-queries/queries/toml.scm
topiary-queries/queries/tree_sitter_query.scm

Discovered while writing the respective blog post.

Various Bash fixes

---

flake.nix

PR based on https://github.com/tweag/topiary/pull/830#discussion_r1923684152

Make flake check removal more explicit

---

flake.lock
flake.nix

Update `flake.lock` to bump our toolchain, etc.

Bump toolchain, etc

---

docs/book/src/SUMMARY.md
docs/book/src/guides/adding-a-new-language.md
docs/book/src/guides/suggested-workflow.md
docs/book/src/guides/yann-tutorial.md

Tidy-up "Guides" section and link to @yannham's tutorial.
Resolves #874

Topiary Book: Tidy-up Guides

---

CONTRIBUTING.md
docs/book/src/SUMMARY.md
docs/book/src/guides/contributing.md
docs/book/src/guides/maturity-policy.md

Move `CONTRIBUTING.md` into the Topiary Book and define a maturity policy for contributed formatting queries. For the latter, since we have no tooling (yet) to do this, I've set the policy as a "rule of thumb": please feel free to challenge and/or add to this :pray:

Topiary Book: Contributing guide

---

.github/pull_request_template.md
docs/book/src/cli/configuration.md
docs/book/src/cli/dialogue.md
docs/book/src/cli/usage/format.md
docs/book/src/cli/usage/index.md
docs/book/src/cli/usage/visualise.md
docs/book/src/getting-started/configuration.md
docs/book/src/getting-started/installation/index.md
docs/book/src/getting-started/installation/package-managers.md
docs/book/src/getting-started/on-tree-sitter.md
docs/book/src/guides/adding-a-new-language.md
docs/book/src/index.md
docs/book/src/installation/index.md
docs/book/src/playground/web.md
docs/book/src/reference/capture-names/indentation.md
docs/book/src/reference/capture-names/index.md
docs/book/src/reference/capture-names/scopes.md
docs/book/src/reference/capture-names/vertical-spacing.md
docs/book/src/reference/language-support.md
docs/book/src/reference/library.md
docs/book/src/reference/related.md
docs/book/style.md

Topiary Book: Editorial sweep

---

docs/book/README.md
docs/book/src/SUMMARY.md
docs/book/src/cli/dialogue.md
docs/book/src/getting-started/on-tree-sitter.md
docs/book/src/playground/web.md
docs/book/src/reference/capture-names/general.md
docs/book/src/reference/capture-names/index.md
docs/book/src/reference/formatting-pipeline.md

Resolves #910
Resolves #912
Applied suggestions that came from initial publication of the Topiary Book:
* Worked example of inadvertent token squashing (mentioned by @facundominguez).
* Overview of the formatting pipeline (mentioned by @torhovland).
* Note about Tree-sitter quantifiers with `@do_nothing` (came up on Discord).
* Also turned the book's "style guide" into a more general `README` for maintainers.

Topiary Book updates

---

dist-workspace.toml

Attempt to get release builds working again

Update dist configuration

---

CHANGELOG.md
Cargo.lock
Cargo.toml
topiary-cli/tests/samples/expected/nickel.ncl
topiary-cli/tests/samples/input/nickel.ncl
topiary-config/Cargo.toml
topiary-config/languages.ncl
topiary-core/benches/benchmark.rs
topiary-queries/Cargo.toml
topiary-queries/queries/nickel.scm

This PR adds support for the newly introduced "include expressions" in Nickel.

Nickel: add support for include expressions

---

docs/book/src/guides/yann-tutorial.md

Book: Added link to Part 2 of Yann's tutorial
